### ISSUE TITLE
trape does not work for windows?

### ISSUE THREAD

**Issue by CrossBrain** [boxug/trape#10]
![image](https://user-images.githubusercontent.com/33381728/32470214-8b358f5c-c324-11e7-9c50-804e93437f88.png)

**Comment by st4nn** [comment]
Check the dependences, because latest version run in Windows,  this video (Spanish) https://youtu.be/ptyuCQmMKiQ was made on Windows

**Comment by st4nn** [comment]
@CrossBrain Do you still have the issue?

**Comment by CrossBrain** [comment]
@st4nn sí :\

**Comment by CrossBrain** [comment]
Yes :\

**Comment by AdrielleKiz** [comment]
@CrossBrain How about enabling the ubuntu subsystem for windows 10 ?
Here's the link for more information [https://msdn.microsoft.com/en-us/commandline/wsl/install-win10](url)

**Comment by CrossBrain** [comment]
[Errno 92] Protocol not available :(
