### ISSUE TITLE
¿Cuál es la versión más estable de python para trabajar en windows y Mac OS?

### ISSUE THREAD

**Issue by chedroid** [boxug/trape#12]
Instale la version 3.7, pero me marca unos errores de codigo en el archivo utils.py, específicamente que la función print ahora debe ir entre paréntesis, le he agregado los paréntesis y posteriormente me da error en db.py con el mensaje de que hay inconsistencia en las tabulaciones(indentación y/o espacios) del código.

**Comment by st4nn** [comment]
Hola @chedroid gracias por escribir,

Trape fue testeado en python 2.7 hasta la versión 3.6

**Comment by chedroid** [comment]
Gracias @st4nn, Ayer logre quitar los bugs del código que se mostraban en la versión 3.6.3 en el archivos db.py eran solo una tabulación de unos if y return. Lo hice en mi equipo pero tengo mac os y solo me muestra un mensaje de bienvenida y no me deja accesar a las funcionalidades porque argumenta que tengo que ser root.

**Comment by st4nn** [comment]
Sí, es un requerimiento funcional que se ejecute en root para que algunas librerías trabajen sin problema

**Comment by chedroid** [comment]
Regrese a windows y todo va bien hasta el momento en el que me sale el mensaje: "Currently no there is support for windows.  No module named urllib2"

**Comment by st4nn** [comment]
Ejecuta esto en tu consola:

`pip install urllib2`

**Comment by chedroid** [comment]
Me da un mensaje que dice que no se encuentra la versión que estoy requiriendo. Que no se encuentra distribución para urllib2.
