### ISSUE TITLE
[x] Error: No module named flask_socketio

### ISSUE THREAD

**Issue by gbiagomba** [boxug/trape#13]
I keep getting this error and I made sure to install the requirements file and I made sure to install flask-socketio. 

![image](https://user-images.githubusercontent.com/5851606/32556141-9ccd8992-c46c-11e7-80c2-0fe6b66e9caf.png)

**Comment by st4nn** [comment]
Hi @gbiagomba, thanks for writing,

You need run this in your console:

`pip install flask_socketio`

And after check the requirements

**Comment by gbiagomba** [comment]
Yeo it worked, thank you!

**Comment by gbiagomba** [comment]
Yep it worked, thank you!

**Comment by gbiagomba** [comment]
Yep it worked, thank you!
