### ISSUE TITLE
Send in Wide Area network by hosting or some other mechanism

### ISSUE THREAD

**Issue by asimajk1** [boxug/trape#14]
How it work for WAN? 
If i want to host it online , what changes are required? Thanks

**Comment by asad316** [comment]
same issue for me.. when i enter lure victim link in my browser it woks fine and shows all my details but if i open it in other system it says "refuse to connect"..
any suggestions?

**Comment by st4nn** [comment]
@asimajk1 please pull again the project because recently we add a commit for solve this issue, Trave server run in LAN network or WAN as well

**Comment by st4nn** [comment]
@asad316 Maybe you need check your ip tables or Firewall rules
