### ISSUE TITLE
trape send file does not work

### ISSUE THREAD

**Issue by eZethNesthrown** [boxug/trape#15]
File located: trape/static/files/file.exe

[  file.exe     | SEND > ]

Does not seem to work.

trape host: Ubuntu Server
Client browser: Google Chrome 61.0.3163.100 & Mozilla Firefox 51.0.1

**Comment by st4nn** [comment]
Hi @eZethNesthrown 

In this video (In Spanish) you may see how send a file to the victim

https://youtu.be/ptyuCQmMKiQ?t=269

Please let me know if you're having troubles still after video

Happy hack
