### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by Hume83** [boxug/trape#19]
Hola, corriendo trape desde window vm con ubuntu, accediendo al GUI de trape desde window
la resolución de IP es incorrecta, no debería tomar el local host sino la IP del host.
En la segunda imagen, se notan resuelve de forma incorrecta las absolute paths de archivos estáticos de google.

Saludos

![error trape 0](https://user-images.githubusercontent.com/11588112/32983266-a3dcb54e-cc70-11e7-895e-6c381691bbd4.jpg)
![error trape 1](https://user-images.githubusercontent.com/11588112/32983265-a385d788-cc70-11e7-84db-bda46f8560ac.jpg)

**Comment by jofpin** [comment]
Vamos a trabajar en una corrección del error, muchas gracias por tu caso.
