### ISSUE TITLE
No victims are caught.

### ISSUE THREAD

**Issue by Bry-fi** [boxug/trape#20]
Basically, when I go to the url that you send to the victims I get nothing. Did I miss a installation step? Becuase I installed all the requirements and followed the simple installation steps and it does not launch. I'm on kali so maybe it doesn't work for kali? Wanted to try this thing out so bad lol.

**Comment by jofpin** [comment]
It works on any operating system, don't you think you've done something wrong? Your opinion is very different from the hundreds of users that have worked for them.
