### ISSUE TITLE
Not a issue but a question!

### ISSUE THREAD

**Issue by Juniorn1003** [boxug/trape#24]
It's a really nice script, it work perfectly.
But I have a question, is it possible over WAN?
And how did you make the python script functioning just by using the web-based GUI?
I am interested in GUI, can you recommend me a tutorial of how I build it?
You may close this.

**Comment by st4nn** [comment]
Hi, and thanks for wrtiting,
1) We tested with [Ngrok](https://ngrok.com/) and works. So there isn't problem if you use it in WAN,
2) Web-based GUI is the same model of Server-Client, we use the script to up a Web server, You may take a look in `stats.py` and `db.py`
3) Depend the language that you want to use, but there is a big community with every language, just ask.
