### ISSUE TITLE
Error: No module named flask

### ISSUE THREAD

**Issue by gabrielwpulido** [boxug/trape#25]
Hi guys, I've installed trape and all dependencies through pip install -r dependencies.txt, but when I run python trape -u www.example.com -p 80 it gaves me this message "Error: No module named flask", So I have no idea which is the problem. Thanks in advance for your help.

**Comment by ubaidsworld** [comment]
@gabrielwpulido You say that you have tried this` pip install -r dependencies.txt `. Please check if `dependencies.txt` has flask included in it or not. It will be better if you use the requirements.txt file from the repository like `pip install -r requirements.txt`. Else install flask with `pip` like `pip install flask`. I guess this will resolve your issue.

**Comment by eghosa02** [comment]
i've a similar problem. the terminal show [x]ERROR: no module named ngrok

**Comment by Mr-Virtual** [comment]
I have aldready instalk flask but still it's giving same error have I have to upgrade the system throught apt-get upgrade

**Comment by vaibhav-rm** [comment]
> i've a similar problem. the terminal show [x]ERROR: no module named ngrok

Its easy just install ngrok .ps just see a totural on youtube how to install ngrok
