### ISSUE TITLE
Vitims not showing up

### ISSUE THREAD

**Issue by SheesAli** [boxug/trape#26]
the victims are not showing up what should i do ?

**Comment by st4nn** [comment]
Hi @SheesAli, can you give us more details please?

**Comment by SheesAli** [comment]
My victim had open link but still no appearing in victim list. I have tried on both Parrot OS and Kali lInux

**Comment by graham30rad** [comment]
Is there any answer's for this? I too am having the same issue, I have tried both the standard ip that trape spits out and also by entering in my public ip . . not a hint of a hit on either . . I have installed all the requirements and tried at least 50 times, still no joy, I'm almost ready to give up :-/
I have also checked my ports are opening and by using my VPN, still nothing! Any help would be greatfull guys..

**Comment by sulemanmalik003** [comment]
Same here. the log victim is not showing up. Any tip?

**Comment by SheesAli** [comment]
The Project is dead I guess.

**Comment by jofpin** [comment]
The project is still alive, pending on early news.
