### ISSUE TITLE
Descarga de Recursos

### ISSUE THREAD

**Issue by daniel2005d** [boxug/trape#28]
Trape a  mi parecer deberia descargar todos los recursos estaticos necesarios para que la página se muestre correctamente. 

Voy a hacer el ajuste y te lo envio.

**Comment by jofpin** [comment]
Quedo atento a tus cambios, gracias!

**Comment by daniel2005d** [comment]
[victim.zip](https://github.com/boxug/trape/files/1664931/victim.zip)
Ya los hice, sin embargo al intentar hacer commit me genera error. 
Lo que hice fue modificar homeVictim de victim.py, y cambiar las rutas absolutas por relativas.

Te adjunto el archivo.

**Comment by daniel2005d** [comment]
Te envvio un ajuste, debido al cambio estaba sobreescribiendo tambien los scripts inyectados.
[victim.zip](https://github.com/boxug/trape/files/1665072/victim.zip)

**Comment by jofpin** [comment]
Voy a probar. Gracias!
