### ISSUE TITLE
OSError

### ISSUE THREAD

**Issue by Isabellle** [boxug/trape#4]
Unfortunately, I get this: 

`OSError: [Errno 1] Operation not permitted: '/var/folders/xv/57736fs93jlgj5pqq5qgwxpw0000gn/T/pip-F4NCOp-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'`

Thanks for any tip

**Comment by Isabellle** [comment]
And `No module named flask_socketio` When typing the command `sudo python trape.py -u https://google.com -p 80
` - Probably due to the previous error

**Comment by Isabellle** [comment]
I ran `pip install flask-socketio` and that's fine :)

**Comment by jofpin** [comment]
Hi, I'm glad you could fix the problem. :)

**Comment by bkuser** [comment]
root@kali:~/tools/trape-master# python trape.py -u http://google.com -p 80

Loading trape...
[x] Error: No module named flask_socketio
root@kali:~/tools/trape-master# D

**Comment by bkuser** [comment]
ya esta ! 
pip2 install flask_socketio

thanks
see ya

**Comment by cachy23** [comment]
Hola. i have the same problem with flask_socketio
if i tip:
            pip install flask_socketio
when a throw TRAPE, shows:
             No module named flask_socketio
and if i tip
            pip2 install flask_socketio
i get this error:
            no module named _internal

any kind of help????? Please

**Comment by fahadali32** [comment]
Loading trape...
[x] ERROR: cannot import name base_manager



Please help what i do now

**Comment by fahadali32** [comment]
anyone### can help me

**Comment by Arslan186** [comment]
@fahadali32 were you able to solve the problem with an error?

**Comment by liverpool66** [comment]
Having the same issues. Has anyone worked out a solution yet?
Loading trape...                            [x] ERROR: cannot import name base_manager

**Comment by aanishr123** [comment]
Loading trape...
[x] ERROR: No module named flask
root@kali:/home/anish/trape# 
got this even after 
root@kali:~# pip install flask
Requirement already satisfied: flask in /usr/local/lib/python3.9/site-packages (1.1.2)
Requirement already satisfied: itsdangerous>=0.24 in /usr/local/lib/python3.9/site-packages (from flask) (1.1.0)
Requirement already satisfied: Jinja2>=2.10.1 in /usr/local/lib/python3.9/site-packages (from flask) (2.11.2)
Requirement already satisfied: click>=5.1 in /usr/local/lib/python3.9/site-packages (from flask) (7.1.1)
Requirement already satisfied: Werkzeug>=0.15 in /usr/local/lib/python3.9/site-packages (from flask) (1.0.1)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.9/site-packages (from Jinja2>=2.10.1->flask) (1.1.1)

**Comment by tonovicio** [comment]
sudo ./trape.py
Traceback (most recent call last):
  File "./trape.py", line 23, in <module>
    from core.utils import utils                  #
  File "/home/marlon/trape/core/utils.py", line 21, in <module>
    import requests, json
ImportError: No module named requests

**Comment by Gokulkannan007** [comment]
Loading trape...
[x] ERROR: No module named flask

i am facing this problem.can anyone help me

**Comment by sunny5478** [comment]
follow pip2 install flask_socketio
then  pip2 install flask_cores

hope it help you

**Comment by rasenshurike** [comment]
Please any one tell me how to solve 
Error:cannot  import base manager

**Comment by pretech86** [comment]
any one fix this issue

**Comment by ONEWHOCANREAD** [comment]
owcr@kali:~/trape$ python trape.py -u https://github.com -p port 8080
Traceback (most recent call last):
  File "trape.py", line 23, in <module>
    from core.utils import utils                  #
  File "/home/owcr/trape/core/utils.py", line 21, in <module>
    import requests , json
ImportError: No module named requests

but 
owcr@kali:~/trape$ pip install requests
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (2.23.0)

how do i solve this issue , i opened the python file and saw nothing wrong with it either

**Comment by abdullzz** [comment]
could not find a version that satisfies the requirement bidict>=0.21.0

**Comment by lucilu1320** [comment]
hey @abdullzz go for:
pip install "Flask-SocketIO<5.0.0"
Hope so this helps!

**Comment by abdullzz** [comment]
@lucilu1320 thanks for the reply. btw i already solved that and got another problem like this 
```
Traceback (most recent call last):
  File "trape.py", line 56, in <module>
    utils.Go(utils.Color['whiteBold'] + "WELCOME " + utils.Color['greenBold'] + os.uname()[1].upper() + utils.Color['whiteBold'] + " TO TRAPE" + utils.Color['white'])
NameError: name 'os' is not defined
```

**Comment by lucilu1320** [comment]
hey @abdullzz go for:
The temporary fix to this issue to run pip install simplejson and go to the C:\....\python27\Lib\site-packages\engineio\client.py file and change the "from json import JSONDecodeError" TO "from simplejson import JSONDecodeError" if using windows distribution.
If you're using linux then go for /usr/local/lib/python2.7/dist-packages/engineio/client.py and change the "from json import JSONDecodeError" TO "from simplejson import JSONDecodeError".

Note: dont change in python 3 or 3.7 it should be python2.7!

Hope this fixes everything!

**Comment by VedantBang26** [comment]
I am getting client error : The client is using an unsupported version of the Socket.IO or Engine.IO protocols (further occurrences of this error will be logged with level INFO)
[2021-08-20 12:39:41,387] ERROR in app: Exception on /get_title [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/root/Desktop/trape/core/stats.py", line 97, in home_get_title
    return json.dumps({'status' : 'OK', 'title' : html})
  File "/usr/local/lib/python3.7/dist-packages/flask/json/__init__.py", line 129, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/dist-packages/flask/json/__init__.py", line 56, in default
    return super().default(o)
  File "/usr/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
 And I m using python3.7 what should I do
