### ISSUE TITLE
Attacks Hooks ? Did this really Work ??

### ISSUE THREAD

**Issue by kali64amd** [boxug/trape#47]
Hi, there

Seems like Attack hooks not working my side, Has anyone have face same issue???

Or We have to pay first?? 

Appreciate your input

Thanks

**Comment by Maxtercam** [comment]
Add Profile At no Coop Danger Miss Add Blog > Patner

**Comment by kali64amd** [comment]
What does it means??

do i have to add profile or something? but where???

**Comment by Maxtercam** [comment]
Observa La pag de los demas Que estan FUll PRo Algo Asi ves!

**Comment by jofpin** [comment]
I invite you to get the professional version at a low cost: write to jofpin@gmail.com
