### ISSUE TITLE
Lure URL not accessible

### ISSUE THREAD

**Issue by harbinc** [boxug/trape#53]
Installation was fine and without error. When I run python trape.py --url https://www.example.com --port 8080 I am able to access the Control Panel login but I am not able to browse the Lure URL. I have tested locally and there are no firewall issues. Confirmed that the process is listening on port 8080. Any advice as to why this isn't working?

**Comment by harbinc** [comment]
Issue resolved. The Lure URL finally loads but very slow.

**Comment by pretech86** [comment]
i face the same issu , what happened with you my dear
