### ISSUE TITLE
Python error?

### ISSUE THREAD

**Issue by PeterStavrou** [boxug/trape#6]
Amazing tool!
Any idea why this is happening?

> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/root/trape/core/victim.py", line 87, in redirectVictim
>     html = victim_inject_code(opener.open(url).read(), 'vscript')
>   File "/usr/lib/python2.7/urllib2.py", line 421, in open
>     protocol = req.get_type()
>   File "/usr/lib/python2.7/urllib2.py", line 283, in get_type
>     raise ValueError, "unknown url type: %s" % self.__original
> ValueError: unknown url type: twitter.com
> 
>

**Comment by almapro** [comment]
Are you typing `twitter.com` instead of `htttps://twitter.com/`?

**Comment by almapro** [comment]
I've already fixed that. I'll add a pull request

**Comment by PeterStavrou** [comment]
Thanks! working now.

**Comment by jofpin** [comment]
We value collaboration very much and we are glad that you work, we will write a commit now.
