### ISSUE TITLE
Trape isn't working with Chromium version 62

### ISSUE THREAD

**Issue by islamTaha12** [boxug/trape#7]
**Description**
I do 
```bash
python trape.py -u https://google.com -p 8080
```
Then I got,
![image](https://user-images.githubusercontent.com/17981089/32416939-22721ee2-c25a-11e7-98f1-88a3085241c9.png)

I tried to browse http://127.0.0.1:8080/google.com in Chromium V.62, but there is **no logs or victims in the cPanal** However, When I used the same URL in **Firefox**, I got logs and I can see the victim in the cPanal.

**OS**
ubuntu 16.04

**Browser**
Version 62.0.3202.62 (Official Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

**Comment by jofpin** [comment]
It is very strange, I run at this time Trape under the same version of Chrome and there is no error.

**Comment by islamTaha12** [comment]
@jofpin I'm wondering what is your os?

**Comment by emans841** [comment]
maybe you edit 127.0.0.1 to your local ip if you are on lan....it works for me

**Comment by jofpin** [comment]
@islamTaha12 my os is ubuntu.

**Comment by CrossBrain** [comment]
Does not work in windows?

**Comment by islamTaha12** [comment]
@emans841 No I didn't' edit it. My localhost=127.0.0.1 and as I said in the issue, It's working with firefox with the same network config.

**Comment by islamTaha12** [comment]
@jofpin I'm wondering How can I run Trap server in my local IP (192.168.1.2) to test it in another machine?

**Comment by Mehran** [comment]
also i wondering how change Lure for the victims: http://127.0.0.1:8080/test.com to my Public ip address ?

**Comment by Highpressure** [comment]
here same with Firefox 56.0.2 while my IE is beeing detected.
@islamTaha12 - for me it works fine connecting to my raspberry coming from my laptop

**Comment by stormxsam** [comment]
@Highpressure can u show how you connect? 
How can i change lure link with my DNS name...can somebody give some guide :)

**Comment by ibrokemycomputer** [comment]
I am running Ubuntu 17.10, and am not seeing any results in the terminal or on the admin page. Attempted with both Chrome 62.0.3202.75 and Firefox 56.0.

**Comment by islamTaha12** [comment]
wooow! I found why the root cause of this issue, In case of there is "Adblock addons" installed, It will block Trap!

You can stop your adds block plugin and test Trap.

**Comment by st4nn** [comment]
@islamTaha12 thanks for sharing
