### ISSUE TITLE
Trape can't dispay media file (in this case picture file)

### ISSUE THREAD

**Issue by zombozo12** [boxug/trape#9]
So, i've been tried to put picture link to trape but trape just shows me what inside the picture which is the raw of the pic. You know, when you open image in notepad or another text editor. So how could it be happen?

**Comment by st4nn** [comment]
@zombozo12  Can you give us further information please? I really don't understand the issue
Thanks for writing

**Comment by zombozo12** [comment]
Thank you for reply my issue, I appreciate so much. Sorry for gave you messy information.

1. I run trape.py and set png url into it. Original link : http://www.catster.com/wp-content/uploads/2017/08/A-fluffy-cat-looking-funny-surprised-or-concerned.jpg

2. I open link that trape processed to be :  http://127.0.0.1:1000/www.catster.com/wp-content/uploads/2017/08/A-fluffy-cat-looking-funny-surprised-or-concerned.jpg . This is how it's looks like

![raw body of image](https://user-images.githubusercontent.com/21243980/32500867-29a1160e-c409-11e7-93e9-be9484575624.png)

Why this is happen? Am I suppose to run trape in server?

**Comment by st4nn** [comment]
Trape will try render the lure like a HTML object, so is better if your Lure url is a webpage, not a picture. If you want just show an image, try this:

```
<html>
	<body>
		<img src="myImage.png" alt="">
	</body>
</html>
```

**Comment by zombozo12** [comment]
I guess I got the problem here. 

> trape renders the lure like a HTML object. 

You shouldn't do that. Try to find another way to render the object to be the original object.
